another system update fix

diff --git a/dotfiles/.scripts/update-system b/dotfiles/.scripts/update-system
--- a/dotfiles/.scripts/update-system
+++ b/dotfiles/.scripts/update-system
@@ -5,17 +5,17 @@ set -euo pipefail
 # --- Configuration ---
 FLAKE_PATH="$HOME/.nix"
 ORIGINAL_DIR=$(pwd) # Used in sudo trap command below
-ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"
+# ZINIT_HOME="${HOME}/.local/share/zinit/zinit.git"
 ACTUAL_USER=${SUDO_USER:-$USER}
 USER_HOME=$(getent passwd "$ACTUAL_USER" | cut -d: -f6)
 
 # Source the zinit script so the 'zinit' command is available
-if [ -f "$ZINIT_HOME/zinit.zsh" ]; then
-    source "$ZINIT_HOME/zinit.zsh"
-else
-    echo "Zinit not found at $ZINIT_HOME"
-    exit 1
-fi
+# if [ -f "$ZINIT_HOME/zinit.zsh" ]; then
+#     source "$ZINIT_HOME/zinit.zsh"
+# else
+#     echo "Zinit not found at $ZINIT_HOME"
+#     exit 1
+# fi
 
 # --- Helper Functions ---
 
